# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.22/ory_0.0.22_macOS_64-bit.tar.gz"
  version "0.0.22"
  sha256 "92658406c68a44b186439b7b2434da3c2805817c354bd53b3edab8bc50debabb"

  def install
    bin.install "ory"
  end
end
