# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/ory/ory/releases/download/v0.0.19/ory_0.0.19_macOS_64-bit.tar.gz"
  version "0.0.19"
  sha256 "0d73c9b7eb1137ba1635542e7d3face62bf5fb4eb3bf4d8b65ad4e5758fe6682"

  def install
    bin.install "ory"
  end
end
