# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ory < Formula
  desc ""
  homepage "https://www.ory.sh"
  version "0.0.63"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ory/cli/releases/download/v0.0.63/ory_0.0.63_macOS_64-bit.tar.gz"
    sha256 "8fbc958827857b6aece3e76680dc3241a9a9c54239445768f31fe38b5530c4bb"
  end

  def install
    bin.install "ory"
  end
end
